# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'demo_Food' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
 inhibit_all_warnings!
  # Pods for demo_Food

  # Redux pods
  pod 'Alamofire', '~> 4.7'
  pod 'SwiftyJSON', '~> 4.0' 
end
